version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '46877:46877'
    volumes:
      - ./:/katyabot
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"