version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .docker.env
    ports:
      - '46877:46877'
    volumes:
      - ./:/katyabot

volumes:
  app: